CREATE TABLE IF NOT EXISTS packages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  licenses TEXT NOT NULL,
  games TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bundles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  store TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'bundle' CHECK (kind IN ('bundle', 'sub', 'giveaway')),
  date TEXT NOT NULL,
  ends TEXT,
  price REAL,
  games TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS free_games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tbl TEXT NOT NULL,
  row_id INTEGER,
  action TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  before TEXT,
  at TEXT NOT NULL
);
